/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'accent-primary': 'var(--color-accent-primary)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-pressed': 'var(--color-accent-pressed)',
        'accent-muted': 'var(--color-accent-muted)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'border': 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        'border-hover': 'var(--color-border-hover)',
        'border-strong': 'var(--color-border-strong)',
        'hairline': 'var(--color-hairline)',
        'surface-resting': 'var(--surface-resting)',
        'surface-raised': 'var(--surface-raised)',
        'surface-hover': 'var(--surface-hover)',
        'surface-pressed': 'var(--surface-pressed)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
        'info': 'var(--color-info)',
        'success-soft': 'var(--color-success-soft)',
        'warning-soft': 'var(--color-warning-soft)',
        'error-soft': 'var(--color-error-soft)',
        'info-soft': 'var(--color-info-soft)',
        'warning-fg': 'var(--color-warning-fg)',
        'intent-high': 'var(--color-intent-high)',
        'intent-medium': 'var(--color-intent-medium)',
        'intent-low': 'var(--color-intent-low)',
        'intent-high-soft': 'var(--color-intent-high-soft)',
        'intent-medium-soft': 'var(--color-intent-medium-soft)',
        'intent-low-soft': 'var(--color-intent-low-soft)',
        'focus-ring': 'var(--color-focus-ring)',
      },
      fontSize: {
        'micro': ['11px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        'caption': ['12px', { lineHeight: '16px', letterSpacing: '0' }],
        'body': ['14px', { lineHeight: '20px', letterSpacing: '0' }],
        'base': ['15px', { lineHeight: '24px', letterSpacing: '0' }],
        'lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em' }],
        'xl': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em' }],
        '2xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'display': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em' }],
      },
      fontFamily: {
        'outfit': ['Outfit', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'num': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'mono': ['Geist Mono', 'JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      spacing: {
        '4.5': '1.125rem',
        '18': '4.5rem',
      },
      borderRadius: {
        'sm': '4px',
        'DEFAULT': '8px',
        'lg': '12px',
        'full': '9999px',
        'control': 'var(--radius-control)',
        'surface': 'var(--radius-surface)',
        'pill': 'var(--radius-pill)',
      },
      maxWidth: {
        'content': 'var(--content-width-max)',
        'prose-tight': 'var(--content-width-prose)',
      },
      boxShadow: {
        'dark': '0 2px 8px 0 rgba(0, 0, 0, 0.4)',
        'dark-sm': '0 1px 4px 0 rgba(0, 0, 0, 0.3)',
        'dark-lg': '0 10px 25px -3px rgba(0, 0, 0, 0.5), 0 4px 6px -2px rgba(0, 0, 0, 0.3)',
        'gold': '0 0 20px rgba(212, 168, 83, 0.3)',
        'gold-lg': '0 0 30px rgba(212, 168, 83, 0.4)',
      },
      transitionDuration: {
        'fast': 'var(--motion-duration-fast)',
        'base': 'var(--motion-duration-base)',
        'slow': 'var(--motion-duration-slow)',
      },
      transitionTimingFunction: {
        'out-soft': 'var(--motion-ease-spring)',
        'out-expo': 'var(--motion-ease-out)',
        'out-spring': 'var(--motion-ease-spring)',
      },
      animation: {
        'slide-up': 'slide-up 0.4s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'shimmer': 'shimmer 2s infinite linear',
      },
    },
  },
  plugins: [],
};
